### PR TITLE
Use `ffmpeg-the-third` crate

### PR DESCRIPTION
**Pull request by zeozeozeo**
[ffmpeg-the-third](https://github.com/shssoichiro/ffmpeg-the-third) is a fork of the abandoned [ffmpeg-next](https://github.com/zmwangx/rust-ffmpeg) crate, which is a fork of the abandoned `ffmpeg` crate, adding features like FFmpeg 5.x and FFmpeg 6.x support.

### CODE REVIEW

**Comment by gerwin3** [comment]
Is there any comment from the original maintainer of ffmpeg-next? I can't seem to find a confirmation that it has gone unmaintained.

**Comment by zeozeozeo** [comment]
> Is there any comment from the original maintainer of ffmpeg-next? I can't seem to find a confirmation that it has gone unmaintained.

not sure really, but sadly it doesn't seem like ffmpeg-next being maintained (last release 8 months ago), PRs are not being merged too.

**Comment by gerwin3** [comment]
Okay, I want to wait this out for a bit since the ffmpeg-the-third crate does not seem to be the de facto replacement just yet. Do agree though that ffmpeg-next seems unmaintained. Will get back to this in a couple months to see if things have changed!

**Comment by gerwin3** [comment]
seems [ffmpeg-next](https://github.com/zmwangx/rust-ffmpeg/commits/master/) is back in business :partying_face:

**Pull request closed without merging**
